### PR TITLE
Delete 3 Front matter sections from .md file

### PR DESCRIPTION
**Pull request by campfire29**
We might want to consider deleting the Abstract, Keywords, and Acknowledgements sections from the .md file. In the docx creation these sections can be included in the Front Pages docx file that will be pasted to the front of the entire docx document. Deletion of these sections would affect the generation of the epub, pdf, etc. documents. Also, removal of these sections from the .md file would hopefully solve the issue of incorrect section references that are generated during the pandoc conversion to docx process.

### CODE REVIEW

**Comment by campfire29** [comment]
Yes, Word is the issue! To proceed for now we can leave the Abstract, Keywords, and Acknowledgements sections in the nistvol8-2.md file. Once the .docx is generated, the following steps should be taken in the docx document:
1. Remove the Abstract, Keywords, and Acknowledgements sections
2. Paste the front pages from the separate docx file (this file contains the Abstract, Keywords, and Acknowledgements sections with the correct formatting)
3. Remove the numbered heading style from the Executive Summary
4. Check the Section references within the text and correct the numbers (e.g., "see Section 6.3" might be changed to "see Section 4.3"). These will be incorrect since Panda assumed that the Executive Summary, Abstract, Keywords, and Acknowledgements sections are numbered (which they are not).

**Comment by campfire29** [comment]
In the md->docx conversion process can we specify that the "Introduction" Section is Section 1? Subsequent sub/sections should be numbered but preceding sections should not be numbered. Is this possible?

**Comment by laszewsk** [comment]
already done.

**Comment by laszewsk** [comment]
headings were converted to bf

**Comment by laszewsk** [comment]
We have the content included, it can be removed in word if needed, however it is better to maintain it in md also

**Pull request closed without merging**
